FreePreview Example/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using FreePreview;

namespace FreePreview_Example.Controllers
{
    public class HomeController : Controller, IPreviewContextProvider
    {
        Models.ExampleContext _context = new Models.ExampleContext();

        public ActionResult Index()
        {
            PreviewSession session = this.GetCurrentPreviewSession();
            return View();
        }

        [StartPreview]
        public ActionResult StartPreview() { return View(); }

        [AuthorizeOrPreview]
        public ActionResult AuthorizedOrPreview()  { return View(); }

        [Authorize]
        public ActionResult AuthorizedOnly() { return View(); }

        [RedirectPreview(AllowAnonymous = true)]
        public ActionResult RedirectPreviewAllowAnonymous() { return View(); }

        [RedirectPreview(PreviewController = "Home", PreviewAction = "StartPreview")]
        public ActionResult RedirectPreviewDenyAnonymous() { return View(); }

        [EndPreview]
        public ActionResult EndPreview() { return View(); }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _context.Dispose();
            base.Dispose(disposing);
        }

        IPreviewContext IPreviewContextProvider.PreviewContext
        {
            get { return _context; }
        }
    }
}

FreePreview Example/Controllers/PreviewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using FreePreview;

using FreePreview_Example.Models;

namespace FreePreview_Example.Controllers
{
    public class PreviewController : Controller
    {
        private ExampleContext db = new ExampleContext();

        // GET: /Preview/
        public ActionResult Index()
        {
            return View(db.PreviewSessions.ToList());
        }

        // GET: /Preview/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PreviewSession previewsession = db.PreviewSessions.Find(id);
            if (previewsession == null)
            {
                return HttpNotFound();
            }
            return View(previewsession);
        }

        // GET: /Preview/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Preview/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,CreatedDate,Active,SessionId")] PreviewSession previewsession)
        {
            if (ModelState.IsValid)
            {
                db.PreviewSessions.Add(previewsession);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(previewsession);
        }

        // GET: /Preview/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PreviewSession previewsession = db.PreviewSessions.Find(id);
            if (previewsession == null)
            {
                return HttpNotFound();
            }
            return View(previewsession);
        }

        // POST: /Preview/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,CreatedDate,Active,SessionId")] PreviewSession previewsession)
        {
            if (ModelState.IsValid)
            {
                db.Entry(previewsession).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(previewsession);
        }

        // GET: /Preview/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PreviewSession previewsession = db.PreviewSessions.Find(id);
            if (previewsession == null)
            {
                return HttpNotFound();
            }
            return View(previewsession);
        }

        // POST: /Preview/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PreviewSession previewsession = db.PreviewSessions.Find(id);
            db.PreviewSessions.Remove(previewsession);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FreePreview Example/Views/Home/AuthorizedOnly.cshtml
@{
    ViewBag.Title = "Authorized Only";
}

<h1>@ViewBag.Title</h1>
<p>
    Welcome to the authorized only section. You should only be able to see this page if you are logged in. Look at the top-right to see you login name and the logout button.
</p>
@Html.Partial("_PreviewActions")

FreePreview Example/Views/Home/AuthorizedOrPreview.cshtml
@{
    ViewBag.Title = "Authorized Or Preview";
}

<h1>@ViewBag.Title</h1>
<p>
    Welcome to the authorized or preview section. This action is available when you are either a logged in user OR have an active preview session. Try either logging out or ending your preview session to see what happens when this action is tried under restricted conditions (you should get the login screen).
</p>
@Html.Partial("_PreviewActions")

FreePreview Example/Views/Home/EndPreview.cshtml
@{
    ViewBag.Title = "End Preview";
}
<h1>@ViewBag.Title</h1>
<p>
    Preview session ended. Now try accessing either an authorized only or preview/authorized action. You should get redirected to the login page.
</p>
@Html.Partial("_PreviewActions")

FreePreview Example/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>@ViewBag.Title</h1>
<p>
    Welcome to Free Preview! A simple way to offer a "no login" demo of your ASP.Net MVC web app.
</p>
<p>
    This demo shows you a contrived example of an app with four actions:
</p>
<ol>
    <li>Start a Session - Starts a new preview session of the app, granting access to the "Authorized or Preview" action, but not granting to the "authorized only" action</li>
    <li>End a Session - Ends the current preview session, if any. This should restrict access for both restricted actions below.</li>
    <li>Authorzed or Preview - This action works if you are a logged in user OR have started a preview session</li>
    <li>Authorized Only - This action is only available if you are logged into the system</li>
</ol>
<p>
    To see the basic functionality, try combinations of th actions below. You can also register to create an account to try the "authorized only" action. Finally, you can see the contents of the Preview Session table in the database using the @Html.ActionLink("Preview Sessions", "Index", "Preview") link on the navbar.
</p>
@Html.Partial("_PreviewActions")

FreePreview Example/Views/Home/RedirectPreviewAllowAnonymous.cshtml
@{
    ViewBag.Title = "RedirectPreviewAllowAnonymous";
}

<h2>Redirect Preview, Allow Anonymous</h2>
<p>
   This action redirects back to the home page if visited by an live preview session; otherwise, it lets anyone in
</p>
@Html.Partial("_PreviewActions")

FreePreview Example/Views/Home/RedirectPreviewDenyAnonymous.cshtml
@{
    ViewBag.Title = "RedirectPreviewAllowAnonymous";
}

<h2>Redirect Preview, Deny Anonymous</h2>
<p>
    This action redirects back to the home page if visited by an live preview session; otherwise, it only lets authenticated users in
</p>
@Html.Partial("_PreviewActions")

FreePreview Example/Views/Home/StartPreview.cshtml
@{
    ViewBag.Title = "Start Preview";
}
<h1>@ViewBag.Title</h1>
<p>
    Preview session started. Now try accessing either an authorized only (access should be denied and you should redirect to login) or preview/authorized action (access should be granted).
</p>
@Html.Partial("_PreviewActions")